title: Blog
author: Baole Fang
theme: minima
navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"
social-network-links:
  email: "baole.fang@gmail.com"
  rss: true  # remove this line if you don't want to show an RSS link at the bottom
  github: baolef